name: Scrape Coinbase Ranking

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user for commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python main.py > file.txt

    - name: Commit and push if changes
      run: |
        git diff --exit-code || git commit -am "Update data"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pAulseperformance/coinbase-appstore-rankings.git HEAD:main