name: Scrape Coinbase Ranking

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit and push if changes
      git add .
      git commit -m "Update data" 
      git push  
    